CREATE TYPE SourceTargetEnum AS ENUM (
    'PT_BR',
    'EN_US',
    'EN_GB',
    'ES_ES',
    'FR_FR',
    'DE_DE',
    'IT_IT',
    'JA_JP',
    'KO_KR',
    'ZH_CN',
    'RU_RU',
    'HI_IN',
    'AR_SA',
    'NL_NL',
    'SV_SE',
    'NO_NO',
    'DA_DK',
    'FI_FI',
    'TR_TR',
    'PL_PL',
    'EL_GR',
    'HE_IL',
    'HU_HU',
    'ID_ID',
    'MS_MY',
    'TH_TH',
    'VI_VN',
    'UK_UA',
    'CS_CZ',
    'SK_SK',
    'RO_RO',
    'BG_BG',
    'HR_HR',
    'SL_SI',
    'LT_LT',
    'LV_LV',
    'ET_EE',
    'SR_RS',
    'MK_MK',
    'SQ_AL',
    'BS_BA',
    'IS_IS',
    'GA_IE',
    'MT_MT',
    'CY_GB',
    'HY_AM',
    'KA_GE',
    'MN_MN',
    'ML_IN',
    'TE_IN',
    'TA_IN'
);

CREATE CAST (varchar AS SourceTargetEnum) WITH INOUT AS IMPLICIT;
    
create table translator (
	id SERIAL primary key,
	name text not null,
	email text not null,
	source_language SourceTargetEnum,
	target_language SourceTargetEnum not null,
 	deleted BOOLEAN not null default false,
    inserted TIMESTAMP not null default current_timestamp,
    updated TIMESTAMP
);

create table document (
	id SERIAL primary key,
	author text not null,
	subject TEXT not null,
	content TEXT not null,
	locale SourceTargetEnum,
	translator INTEGER not null references translator(id),
 	deleted BOOLEAN not null default false,
    inserted TIMESTAMP not null default current_timestamp,
    updated TIMESTAMP
);
